baseURL = "https://MaggieSueWoW.github.io/QuartzTWWS1/"
languageCode = "en-us"
title = ''
theme = "ananke"
copyright = "MaggieSue"

publishDir = "docs"

[params]
  author = "MaggieSueWoW"
  description = "Charts for the WoW team 'Quartz' during 'The War Within' (TWW) - Season 1"
  enableDarkMode = true
  custom_css = ["custom.css"]
  body_classes = "sans-serif bg-dark-gray"
  text_color = "near-white"
  omit_header_text = false

